# Generated by Django 6.0.2 on 2026-02-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='permissao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='permissao_base',
            field=models.BooleanField(default=False),
        ),
    ]
