# Generated by Django 6.0.2 on 2026-02-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usuario_permissao_usuario_permissao_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='permissao_base',
            new_name='permissao_a',
        ),
        migrations.AddField(
            model_name='usuario',
            name='permissao_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app.empresa'),
        ),
    ]
