# Generated by Django 6.0.2 on 2026-02-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_permissao_a_usuario_permissao_adiantamentos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permissao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="permissoes",
            field=models.ManyToManyField(blank=True, to="app.permissao"),
        ),
    ]
