# Generated by Django 6.0.2 on 2026-02-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_permissao_usuario_permissoes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_menu_inicial",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_versao_sistema",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_comite_diario",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_balanco_patrimonial",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_dre",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_contas_a_receber",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_dfc",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_adiantamentos",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_contratos_redes",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_plano_cargos_salarios",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_descritivos",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_lista_atividades",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_fiscal_contabil",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_faturamento",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_apuracao_resultados",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_orcamento_budget",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_carteira",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_pedidos_pendentes",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_vendas_categoria",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_precificacao",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_controle_margem",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_cargas_aberto",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_operador_logistico",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_tabela_fretes",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_estoque_pcp",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="permissao_producao",
        ),
    ]
