# Generated by Django 6.0.2 on 2026-02-14 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_usuario_campos_permissoes_legadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='semana_de_prazo',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)]),
        ),
    ]
