# Generated by Django 6.0.2 on 2026-02-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_atividade_semana_de_prazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(default='', max_length=4, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(default='', max_length=7, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regioes', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_faturado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultima_venda', models.DateField(blank=True, null=True)),
                ('qtd_dias_sem_venda', models.PositiveIntegerField(default=0)),
                ('intervalo', models.CharField(blank=True, default='', max_length=20)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('gerente', models.CharField(blank=True, default='', max_length=150)),
                ('vendedor', models.CharField(blank=True, default='', max_length=150)),
                ('descricao_perfil', models.CharField(blank=True, default='', max_length=200)),
                ('nome_parceiro', models.CharField(blank=True, default='', max_length=150)),
                ('ativo_indicador', models.BooleanField(default=True)),
                ('cliente_indicador', models.BooleanField(default=False)),
                ('fornecedor_indicador', models.BooleanField(default=False)),
                ('transporte_indicador', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteiras', to='app.empresa')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.regiao')),
            ],
        ),
    ]
