# Generated by Django 6.0.2 on 2026-02-15 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cidade_regiao_carteira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteira',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
