# Generated by Django 6.0.2 on 2026-02-16 13:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_carteira_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_notas', models.PositiveIntegerField()),
                ('custo_medio_icms_cmv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_venda', models.DateField(default=django.utils.timezone.localdate)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='app.empresa')),
            ],
        ),
    ]
