# Generated by Django 6.0.2 on 2026-02-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='descricao',
            field=models.CharField(default='', max_length=200),
        ),
    ]
