# Generated by Django 6.0.2 on 2026-02-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_venda_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="codigo",
            field=models.CharField(max_length=50),
        ),
    ]
