# Generated by Django 6.0.2 on 2026-02-16 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_venda_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=20)),
                ('ordem_de_carga_codigo', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_prevista_saida', models.DateField()),
                ('data_chegada', models.DateField(blank=True, null=True)),
                ('data_finalizacao', models.DateField(blank=True, null=True)),
                ('nome_motorista', models.CharField(blank=True, default='', max_length=150)),
                ('nome_fantasia_empresa', models.CharField(max_length=150)),
                ('prazo_maximo_dias', models.PositiveIntegerField(default=0)),
                ('idade_dias', models.PositiveIntegerField(default=0)),
                ('verificacao', models.BooleanField(default=False)),
                ('critica', models.CharField(blank=True, default='', max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='app.empresa')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.regiao')),
            ],
        ),
    ]
