# Generated by Django 6.0.2 on 2026-02-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cargas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargas',
            name='critica',
        ),
        migrations.RemoveField(
            model_name='cargas',
            name='idade_dias',
        ),
        migrations.RemoveField(
            model_name='cargas',
            name='verificacao',
        ),
    ]
