# Generated by Django 6.0.2 on 2026-02-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_cargas_critica_remove_cargas_idade_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargas',
            name='prazo_maximo_dias',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
