# Generated by Django 6.0.2 on 2026-02-17 13:48

import django.db.models.deletion
from django.db import migrations, models


def migrar_nome_parceiro_para_fk(apps, schema_editor):
    Carteira = apps.get_model("app", "Carteira")
    Parceiro = apps.get_model("app", "Parceiro")
    db_alias = schema_editor.connection.alias

    cache_por_empresa = {}
    carteiras = list(
        Carteira.objects.using(db_alias)
        .exclude(nome_parceiro="")
        .values("id", "empresa_id", "nome_parceiro")
    )
    for carteira in carteiras:
        nome = (carteira.get("nome_parceiro") or "").strip()
        if not nome:
            continue

        chave_empresa = carteira.get("empresa_id")
        mapa_empresa = cache_por_empresa.setdefault(chave_empresa, {})
        parceiro_id = mapa_empresa.get(nome)
        if parceiro_id is None:
            sequencia = len(mapa_empresa) + 1
            codigo = f"LEGADO-{sequencia}"
            while Parceiro.objects.using(db_alias).filter(empresa_id=chave_empresa, codigo=codigo).exists():
                sequencia += 1
                codigo = f"LEGADO-{sequencia}"

            parceiro = Parceiro.objects.using(db_alias).create(
                empresa_id=chave_empresa,
                nome=nome,
                codigo=codigo,
            )
            parceiro_id = parceiro.id
            mapa_empresa[nome] = parceiro_id

        Carteira.objects.using(db_alias).filter(id=carteira.get("id")).update(parceiro_id=parceiro_id)


def reverso_migracao_nome_parceiro(apps, schema_editor):
    Carteira = apps.get_model("app", "Carteira")
    db_alias = schema_editor.connection.alias
    carteiras = list(
        Carteira.objects.using(db_alias)
        .values("id", "parceiro__nome")
    )
    for carteira in carteiras:
        nome_parceiro = carteira.get("parceiro__nome") or ""
        Carteira.objects.using(db_alias).filter(id=carteira.get("id")).update(nome_parceiro=nome_parceiro)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_cargas_prazo_maximo_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parceiros', to='app.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='carteira',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteiras', to='app.parceiro'),
        ),
        migrations.RunPython(
            migrar_nome_parceiro_para_fk,
            reverso_migracao_nome_parceiro,
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='nome_parceiro',
        ),
        migrations.AddConstraint(
            model_name='parceiro',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_parceiro_empresa_codigo'),
        ),
    ]
