# Generated by Django 6.0.2 on 2026-02-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_carteira_nome_parceiro_parceiro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.CharField(default='', max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naturezas', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao_codigo', models.CharField(max_length=50)),
                ('descricao_receita_despesa', models.CharField(default='', max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_titulo_codigo', models.CharField(max_length=50)),
                ('descricao', models.CharField(default='', max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='FluxoDeCaixaDFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_negociacao', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_nota', models.CharField(blank=True, default='', max_length=50)),
                ('descricao_centro_resultado', models.CharField(blank=True, default='', max_length=200)),
                ('descricao_tipo_operacao', models.CharField(blank=True, default='', max_length=100)),
                ('historico', models.TextField(blank=True, default='')),
                ('tipo_movimento', models.CharField(blank=True, default='', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_de_caixa_dfc', to='app.empresa')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.parceiro')),
                ('natureza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.natureza')),
                ('operacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.operacao')),
                ('titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.titulo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='natureza',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_natureza_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='operacao',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_operacao_codigo'), name='uq_operacao_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='titulo',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_titulo_codigo'), name='uq_titulo_empresa_codigo'),
        ),
    ]
