# Generated by Django 6.0.2 on 2026-02-18 00:00

import django.db.models.deletion
from django.db import migrations, models


def _migrar_centro_resultado_dfc(apps, schema_editor):
    FluxoDeCaixaDFC = apps.get_model("app", "FluxoDeCaixaDFC")
    CentroResultado = apps.get_model("app", "CentroResultado")

    for fluxo in FluxoDeCaixaDFC.objects.exclude(descricao_centro_resultado="").iterator():
        descricao = (fluxo.descricao_centro_resultado or "").strip()
        if not descricao:
            continue
        centro_resultado, _ = CentroResultado.objects.get_or_create(
            empresa_id=fluxo.empresa_id,
            descricao=descricao,
        )
        fluxo.centro_resultado_id = centro_resultado.id
        fluxo.save(update_fields=["centro_resultado"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_natureza_operacao_titulo_fluxodecaixadfc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroResultado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=200)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centros_resultado",
                        to="app.empresa",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="centroresultado",
            constraint=models.UniqueConstraint(
                fields=("empresa", "descricao"),
                name="uq_centro_resultado_empresa_descricao",
            ),
        ),
        migrations.AddField(
            model_name="fluxodecaixadfc",
            name="centro_resultado",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.centroresultado"),
        ),
        migrations.RunPython(_migrar_centro_resultado_dfc, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="fluxodecaixadfc",
            name="descricao_centro_resultado",
        ),
        migrations.CreateModel(
            name="ContasAReceber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_negociacao", models.DateField()),
                ("data_vencimento", models.DateField()),
                ("data_arquivo", models.DateField(blank=True, null=True)),
                ("nome_fantasia_empresa", models.CharField(blank=True, default="", max_length=200)),
                ("numero_nota", models.CharField(blank=True, default="", max_length=50)),
                ("valor_desdobramento", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("valor_liquido", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "centro_resultado",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.centroresultado"),
                ),
                (
                    "empresa",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contas_a_receber", to="app.empresa"),
                ),
                (
                    "natureza",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.natureza"),
                ),
                (
                    "operacao",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.operacao"),
                ),
                (
                    "parceiro",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.parceiro"),
                ),
                (
                    "titulo",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.titulo"),
                ),
            ],
        ),
    ]
