# Generated by Django 6.0.2 on 2026-02-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_centroresultado_contasareceber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contasareceber",
            name="vendedor",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
