# Generated by Django 6.0.1 on 2026-02-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_remove_fluxodecaixadfc_descricao_tipo_operacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_vencimento", models.DateField()),
                ("data_baixa", models.DateField()),
                ("valor_baixa", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_liquido", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_desdobramento", models.DecimalField(decimal_places=2, max_digits=10)),
                ("centro_resultado", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.centroresultado")),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="orcamentos", to="app.empresa")),
                ("natureza", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.natureza")),
                ("operacao", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.operacao")),
                ("parceiro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.parceiro")),
                ("titulo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.titulo")),
            ],
        ),
    ]
