# Generated by Django 6.0.1 on 2026-02-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_orcamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="nome_empresa",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.CreateModel(
            name="OrcamentoPlanejado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_empresa", models.CharField(blank=True, default="", max_length=200)),
                ("ano", models.PositiveSmallIntegerField()),
                ("janeiro", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("fevereiro", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("marco", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("abril", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("maio", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("junho", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("julho", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("agosto", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("setembro", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("outubro", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("novembro", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("dezembro", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("centro_resultado", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.centroresultado")),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="orcamentos_planejados", to="app.empresa")),
                ("natureza", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.natureza")),
            ],
        ),
    ]
