# Generated by Django 6.0.1 on 2026-02-19

import django.db.models.deletion
from django.db import migrations, models


CENTRO_RESULTADO_PADRAO = "<SEM CENTRO DE RESULTADO>"


def preencher_centro_resultado_nulo(apps, schema_editor):
    Orcamento = apps.get_model("app", "Orcamento")
    CentroResultado = apps.get_model("app", "CentroResultado")
    db_alias = schema_editor.connection.alias

    empresas_ids = (
        Orcamento.objects.using(db_alias)
        .filter(centro_resultado__isnull=True)
        .values_list("empresa_id", flat=True)
        .distinct()
    )

    for empresa_id in empresas_ids:
        centro_resultado, _ = CentroResultado.objects.using(db_alias).get_or_create(
            empresa_id=empresa_id,
            descricao=CENTRO_RESULTADO_PADRAO,
        )
        Orcamento.objects.using(db_alias).filter(
            empresa_id=empresa_id,
            centro_resultado__isnull=True,
        ).update(centro_resultado_id=centro_resultado.id)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_orcamentoplanejado_orcamento_nome_empresa"),
    ]

    operations = [
        migrations.RunPython(preencher_centro_resultado_nulo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="orcamento",
            name="centro_resultado",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="app.centroresultado"),
        ),
    ]
