# Generated by Django 6.0.2 on 2026-02-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_orcamento_centro_resultado_obrigatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=80)),
                ('descricao_produto', models.CharField(blank=True, default='', max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_origem', models.CharField(blank=True, default='', max_length=255)),
                ('numero_operacao', models.PositiveIntegerField()),
                ('situacao', models.CharField(blank=True, default='', max_length=100)),
                ('tamanho_lote', models.CharField(blank=True, default='', max_length=80)),
                ('numero_lote', models.CharField(blank=True, default='', max_length=80)),
                ('data_hora_entrada_atividade', models.DateTimeField(blank=True, null=True)),
                ('data_hora_aceite_atividade', models.DateTimeField(blank=True, null=True)),
                ('data_hora_inicio_atividade', models.DateTimeField(blank=True, null=True)),
                ('data_hora_fim_atividade', models.DateTimeField(blank=True, null=True)),
                ('kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('producao_por_dia', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('kg_por_lote', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to='app.empresa')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes', to='app.produto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_produto'), name='uq_produto_empresa_codigo'),
        ),
    ]
