# Generated by Django 6.0.2 on 2026-02-21 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_produto_producao_produto_uq_produto_empresa_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=10, unique=True)),
                ('sigla', models.CharField(max_length=5)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_federativas', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_frete_comercial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_hora_alteracao', models.DateTimeField(blank=True, null=True)),
                ('valor_frete_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_frete_tonelada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipo_frete', models.CharField(blank=True, default='', max_length=30)),
                ('valor_frete_por_km', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('valor_taxa_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('venda_minima', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fretes', to='app.cidade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fretes', to='app.empresa')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fretes', to='app.regiao')),
                ('unidade_federativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fretes', to='app.unidadefederativa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cidade'), name='uq_frete_empresa_cidade')],
            },
        ),
    ]
