# Generated by Django 6.0.2 on 2026-02-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_unidadefederativa_frete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_origem', models.DateField()),
                ('data_contagem', models.DateField()),
                ('status', models.CharField(blank=True, default='Ativo', max_length=30)),
                ('codigo_empresa', models.CharField(blank=True, default='', max_length=20)),
                ('qtd_estoque', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('giro_mensal', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('lead_time_fornecimento', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('codigo_voume', models.CharField(blank=True, default='', max_length=20)),
                ('custo_total', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('reservado', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('pacote_por_fardo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('sub_total_est_pen', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('producao_por_dia_fd', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('total_pcp_pacote', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('total_pcp_fardo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('dia_de_producao', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('codigo_local', models.CharField(blank=True, default='', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='app.empresa')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoques', to='app.produto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nome_origem', 'data_contagem', 'codigo_empresa', 'codigo_local', 'produto'), name='uq_estoque_empresa_origem_contagem_local_produto')],
            },
        ),
    ]
