# Generated by Django 6.0.2 on 2026-02-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_estoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="producao",
            name="estoque_minimo_pacote",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
