# Generated by Django 6.0.2 on 2026-02-24 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_produto_parametros_completos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_motorista', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motoristas', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transportadora', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportadoras', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(default=django.utils.timezone.localdate)),
                ('numero_unico', models.CharField(max_length=80)),
                ('previsao_carregamento', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='app.empresa')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas', to='app.motorista')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas', to='app.transportadora')),
            ],
        ),
        migrations.AddConstraint(
            model_name='motorista',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_motorista'), name='uq_motorista_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='transportadora',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_transportadora'), name='uq_transportadora_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='agenda',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_unico'), name='uq_agenda_empresa_numero_unico'),
        ),
    ]
