# Generated by Django 6.0.2 on 2026-02-24 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_motorista_transportadora_agenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parceiros', to='app.cidade'),
        ),
    ]
