# Generated by Django 6.0.2 on 2026-02-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_parceiro_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rota', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='app.empresa')),
                ('uf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas', to='app.unidadefederativa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'codigo_rota'), name='uq_rota_empresa_codigo')],
            },
        ),
    ]
