# Generated by Django 6.0.2 on 2026-02-24 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rota'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS app_pedidopendente;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='PedidoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unico', models.CharField(max_length=80)),
                ('rota_texto', models.CharField(blank=True, default='', max_length=200)),
                ('regiao_texto', models.CharField(blank=True, default='', max_length=200)),
                ('valor_tonelada_frete_safia', models.CharField(blank=True, default='', max_length=80)),
                ('pendente', models.CharField(blank=True, default='', max_length=30)),
                ('nome_cidade_parceiro_safia', models.CharField(blank=True, default='', max_length=150)),
                ('previsao_entrega', models.DateField(blank=True, null=True)),
                ('dt_neg', models.DateField(blank=True, null=True)),
                ('prazo_maximo', models.PositiveSmallIntegerField(default=3)),
                ('tipo_venda', models.CharField(blank=True, default='', max_length=80)),
                ('nome_empresa', models.CharField(blank=True, default='', max_length=220)),
                ('cod_nome_parceiro', models.CharField(blank=True, default='', max_length=220)),
                ('vlr_nota', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('peso_liq_itens', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('apelido_vendedor', models.CharField(blank=True, default='', max_length=150)),
                ('gerente', models.CharField(blank=True, default='', max_length=150)),
                ('data_para_calculo', models.DateField(blank=True, null=True)),
                ('descricao_tipo_negociacao', models.CharField(blank=True, default='', max_length=220)),
                ('nro_nota', models.BigIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_pendentes', to='app.empresa')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_pendentes', to='app.parceiro')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_pendentes', to='app.regiao')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_pendentes', to='app.rota')),
            ],
        ),
    ]
