# Generated by Django 6.0.2 on 2026-02-25 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_empresa_possui_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleMargem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_origem', models.CharField(blank=True, default='', max_length=120)),
                ('nro_unico', models.BigIntegerField(db_index=True)),
                ('nome_empresa', models.CharField(blank=True, default='', max_length=220)),
                ('cod_nome_parceiro', models.CharField(blank=True, default='', max_length=220)),
                ('descricao_perfil', models.CharField(blank=True, max_length=220, null=True)),
                ('apelido_vendedor', models.CharField(blank=True, max_length=150, null=True)),
                ('gerente', models.CharField(blank=True, max_length=150, null=True)),
                ('dt_neg', models.DateField(blank=True, null=True)),
                ('previsao_entrega', models.DateField(blank=True, null=True)),
                ('tipo_venda', models.CharField(blank=True, max_length=80, null=True)),
                ('vlr_nota', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('custo_total_produto', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('margem_bruta', models.DecimalField(decimal_places=9, default=0, max_digits=16)),
                ('lucro_bruto', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('valor_tonelada_frete_safia', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('peso_bruto', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('custo_por_kg', models.DecimalField(decimal_places=9, default=0, max_digits=16)),
                ('vendas', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('producao', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('operador_logistica', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('frete_distribuicao', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('total_logistica', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('administracao', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('financeiro', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('total_setores', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('valor_liquido', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('margem_liquida', models.DecimalField(decimal_places=9, default=0, max_digits=16)),
                ('situacao', models.CharField(choices=[('AMARELO', 'Amarelo'), ('ROXO', 'Roxo'), ('VERDE', 'Verde'), ('VERMELHO', 'Vermelho')], default='AMARELO', max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_margem', to='app.empresa')),
                ('parceiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_margem', to='app.parceiro')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nro_unico'), name='uq_controle_margem_empresa_nro_unico')],
            },
        ),
    ]
