# Generated by Django 6.0.2 on 2026-02-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_controlemargem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlemargem',
            name='situacao',
        ),
    ]
