# Generated by Django 6.0.2 on 2026-02-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_controlemargem_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroMargemAdministracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(default='Administracao', max_length=80)),
                ('remuneracao_percentual', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametro_margem_administracao', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroMargemFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(default='Contas a Receber', max_length=80)),
                ('taxa_ao_mes', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametro_margem_financeiro', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroMargemLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(default='Operador Logistico', max_length=80)),
                ('criterio', models.CharField(default='Entrega+Balcao', max_length=120)),
                ('remuneracao_rs', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametro_margem_logistica', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroMargemVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(default='Vendas', max_length=80)),
                ('criterio', models.CharField(default='Geral', max_length=120)),
                ('remuneracao_percentual', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametro_margem_vendas', to='app.empresa')),
            ],
        ),
    ]
