# Generated by Django 6.0.2 on 2026-02-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_parametromargemadministracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametromargemfinanceiro',
            name='remuneracao_percentual',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametromargemfinanceiro',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_margem_financeiro', to='app.empresa'),
        ),
        migrations.AlterField(
            model_name='parametromargemlogistica',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_margem_logistica', to='app.empresa'),
        ),
        migrations.AlterField(
            model_name='parametromargemvendas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_margem_vendas', to='app.empresa'),
        ),
    ]
