# Generated by Django 6.0.2 on 2026-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_atividade_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='codigo_voume',
            field=models.CharField(blank=True, db_column='codigo_voume', default='', max_length=20),
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='codigo_voume',
            new_name='codigo_volume',
        ),
    ]
