# Generated by Django 6.0.2 on 2026-03-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_faturamento"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Faturamento",
        ),
        migrations.CreateModel(
            name="Faturamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_origem", models.CharField(blank=True, default="", max_length=120)),
                ("data_faturamento", models.DateField()),
                ("nome_empresa", models.CharField(blank=True, default="", max_length=220)),
                ("numero_nota", models.BigIntegerField(db_column="nro_nota", default=0)),
                ("indice_produto", models.PositiveIntegerField(db_column="indice_produto", default=1)),
                ("valor_nota", models.DecimalField(db_column="vlr_nota", decimal_places=2, default=0, max_digits=16)),
                ("participacao_venda_geral", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("participacao_venda_cliente", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("valor_nota_unico", models.DecimalField(db_column="vlr_nota_unico", decimal_places=2, default=0, max_digits=16)),
                ("peso_bruto", models.DecimalField(db_column="peso_bruto", decimal_places=2, default=0, max_digits=16)),
                ("peso_bruto_unico", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("quantidade_volumes", models.DecimalField(db_column="qtd_volumes", decimal_places=2, default=0, max_digits=16)),
                ("quantidade_saida", models.DecimalField(db_column="qtd_saida", decimal_places=2, default=0, max_digits=16)),
                ("status_nfe", models.CharField(blank=True, default="", max_length=80)),
                ("apelido_vendedor", models.CharField(blank=True, default="", max_length=150)),
                ("tipo_movimento", models.CharField(blank=True, default="", max_length=80)),
                ("prazo_medio_safia", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("media_unica", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("tipo_venda", models.CharField(blank=True, default="", max_length=120)),
                ("gerente", models.CharField(blank=True, default="", max_length=150)),
                ("descricao_perfil", models.CharField(blank=True, default="", max_length=220)),
                ("valor_frete", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_column="criado_em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, db_column="atualizado_em")),
                ("centro_resultado", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.centroresultado")),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="faturamentos", to="app.empresa")),
                ("natureza", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.natureza")),
                ("operacao", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.operacao")),
                ("parceiro", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="faturamentos", to="app.parceiro")),
                ("produto", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="faturamentos", to="app.produto")),
            ],
        ),
    ]
