# Generated by Django 6.0.2 on 2026-03-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_dfcsaldomanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=220)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descricoes_perfil', to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_acabado_percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('valor_meta_pd_acabado', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('meta_mt_prima_percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('descricao_perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametros_metas', to='app.descricaoperfil')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_metas', to='app.empresa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='descricaoperfil',
            constraint=models.UniqueConstraint(fields=('empresa', 'descricao'), name='uq_descricao_perfil_empresa_descricao'),
        ),
        migrations.AddConstraint(
            model_name='parametrometa',
            constraint=models.UniqueConstraint(fields=('empresa', 'descricao_perfil'), name='uq_parametro_meta_empresa_perfil'),
        ),
    ]
