# Generated by Django 6.0.2 on 2026-03-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_descricaoperfil_parametrometa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoCargoSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastro', models.PositiveIntegerField()),
                ('funcionario', models.CharField(max_length=150)),
                ('contrato', models.CharField(blank=True, default='', max_length=80)),
                ('genero', models.CharField(blank=True, default='', max_length=40)),
                ('setor', models.CharField(blank=True, default='', max_length=150)),
                ('cargo', models.CharField(blank=True, default='', max_length=180)),
                ('novo_cargo', models.CharField(blank=True, default='', max_length=180)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('salario_carteira', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('piso_categoria', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('jr', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('pleno', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('senior', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_cargos_salarios', to='app.empresa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'cadastro'), name='uq_plano_cargo_salario_empresa_cadastro')],
            },
        ),
    ]
