# Generated by Django 6.0.2 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_planocargosalario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Descritivo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inicio", models.TimeField()),
                ("termino", models.TimeField()),
                ("contas_a_pagar", models.TextField(blank=True, default="")),
                ("contas_a_receber", models.TextField(blank=True, default="")),
                ("supervisor_financeiro", models.TextField(blank=True, default="")),
                ("faturamento", models.TextField(blank=True, default="")),
                ("supervisor_logistica", models.TextField(blank=True, default="")),
                ("conferente", models.TextField(blank=True, default="")),
                ("gerente_de_producao", models.TextField(blank=True, default="")),
                ("gerente_cml", models.TextField(blank=True, default="")),
                ("assistente_comercial", models.TextField(blank=True, default="")),
                ("diretor", models.TextField(blank=True, default="")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descritivos",
                        to="app.empresa",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "inicio", "termino"),
                        name="uq_descritivo_empresa_inicio_termino",
                    ),
                ],
            },
        ),
    ]
