# Generated by Django 6.0.2 on 2026-03-27 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_descritivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.IntegerField()),
                ('numero_conta', models.BigIntegerField()),
                ('nome_banco', models.CharField(max_length=150)),
                ('nome_empresa_fantasia', models.PositiveSmallIntegerField(choices=[(1, 'SAFIA DISTRIBUIDORA'), (2, 'COMERCIAL ARAGUAIA'), (4, 'CSM TRANSPORTES')])),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias', to='app.empresa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'agencia', 'numero_conta'), name='uq_conta_bancaria_empresa_agencia_conta')],
            },
        ),
    ]
