# Generated by Django 6.0.2 on 2026-03-27

import django.db.models.deletion
from django.db import migrations, models


EMPRESAS_TITULARES_PADRAO = {
    1: "SAFIA DISTRIBUIDORA",
    2: "COMERCIAL ARAGUAIA",
    4: "CSM TRANSPORTES",
}


def popular_empresas_titulares_e_vincular_contas(apps, schema_editor):
    Empresa = apps.get_model("app", "Empresa")
    EmpresaTitular = apps.get_model("app", "EmpresaTitular")
    ContaBancaria = apps.get_model("app", "ContaBancaria")

    def garantir_titular(empresa_id, codigo):
        if not empresa_id or not codigo:
            return None
        nome = EMPRESAS_TITULARES_PADRAO.get(int(codigo), f"EMPRESA {codigo}")
        titular, _ = EmpresaTitular.objects.get_or_create(
            empresa_id=empresa_id,
            codigo=int(codigo),
            defaults={"nome": nome},
        )
        return titular

    if Empresa.objects.filter(id=3).exists():
        for codigo_padrao in EMPRESAS_TITULARES_PADRAO:
            garantir_titular(3, codigo_padrao)

    contas = ContaBancaria.objects.all().only("id", "empresa_id", "nome_empresa_fantasia")
    for conta in contas.iterator():
        codigo = int(getattr(conta, "nome_empresa_fantasia", 0) or 0)
        titular = garantir_titular(conta.empresa_id, codigo)
        if titular is None:
            continue
        ContaBancaria.objects.filter(id=conta.id).update(empresa_titular_id=titular.id)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_contabancaria"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmpresaTitular",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.PositiveSmallIntegerField()),
                ("nome", models.CharField(max_length=120)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas_titulares",
                        to="app.empresa",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("empresa", "codigo"), name="uq_empresa_titular_empresa_codigo"),
                    models.UniqueConstraint(fields=("empresa", "nome"), name="uq_empresa_titular_empresa_nome"),
                ],
            },
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="empresa_titular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contas_bancarias",
                to="app.empresatitular",
            ),
        ),
        migrations.RunPython(
            code=popular_empresas_titulares_e_vincular_contas,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="contabancaria",
            name="empresa_titular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contas_bancarias",
                to="app.empresatitular",
            ),
        ),
        migrations.RemoveField(
            model_name="contabancaria",
            name="nome_empresa_fantasia",
        ),
        migrations.CreateModel(
            name="SaldoLimite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.DateField()),
                (
                    "tipo_movimentacao",
                    models.CharField(
                        choices=[
                            ("saldo_inicial", "Saldo Inicial"),
                            ("limite_inicial", "Limite Inicial"),
                            ("saldo_final", "Saldo Final"),
                            ("limite_final", "Limite Final"),
                            ("antecipacao", "Antecipacao"),
                        ],
                        max_length=32,
                    ),
                ),
                ("valor_atual", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "conta_bancaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saldos_limites",
                        to="app.contabancaria",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saldos_limites",
                        to="app.empresa",
                    ),
                ),
                (
                    "empresa_titular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saldos_limites",
                        to="app.empresatitular",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "data", "empresa_titular", "conta_bancaria", "tipo_movimentacao"),
                        name="uq_saldo_limite_registro",
                    ),
                ],
            },
        ),
    ]
