# Generated by Django 6.0.2 on 2026-03-30

import django.db.models.deletion
from django.db import migrations, models


BANCO_NOME_FALLBACK = "BANCO NAO INFORMADO"


def popular_bancos_e_vincular_contas(apps, schema_editor):
    Banco = apps.get_model("app", "Banco")
    ContaBancaria = apps.get_model("app", "ContaBancaria")

    cache_banco_id_por_empresa_nome = {}

    contas = ContaBancaria.objects.all().only("id", "empresa_id", "nome_banco")
    for conta in contas.iterator():
        nome_banco = (getattr(conta, "nome_banco", "") or "").strip() or BANCO_NOME_FALLBACK
        chave = (conta.empresa_id, nome_banco.casefold())

        banco_id = cache_banco_id_por_empresa_nome.get(chave)
        if not banco_id:
            banco = (
                Banco.objects.filter(empresa_id=conta.empresa_id, nome__iexact=nome_banco)
                .order_by("id")
                .first()
            )
            if banco is None:
                banco = Banco.objects.create(empresa_id=conta.empresa_id, nome=nome_banco)
            banco_id = banco.id
            cache_banco_id_por_empresa_nome[chave] = banco_id

        ContaBancaria.objects.filter(id=conta.id).update(banco_id=banco_id)


def restaurar_nome_banco(apps, schema_editor):
    Banco = apps.get_model("app", "Banco")
    ContaBancaria = apps.get_model("app", "ContaBancaria")

    nomes_por_banco_id = dict(Banco.objects.values_list("id", "nome"))

    contas = ContaBancaria.objects.all().only("id", "banco_id")
    for conta in contas.iterator():
        nome_banco = (nomes_por_banco_id.get(conta.banco_id) or "").strip()
        ContaBancaria.objects.filter(id=conta.id).update(nome_banco=nome_banco)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_empresatitular_saldolimite_refactor_contabancaria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=150)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bancos",
                        to="app.empresa",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("empresa", "nome"), name="uq_banco_empresa_nome"),
                ],
            },
        ),
        migrations.AddField(
            model_name="contabancaria",
            name="banco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contas_bancarias",
                to="app.banco",
            ),
        ),
        migrations.RunPython(
            code=popular_bancos_e_vincular_contas,
            reverse_code=restaurar_nome_banco,
        ),
        migrations.AlterField(
            model_name="contabancaria",
            name="banco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contas_bancarias",
                to="app.banco",
            ),
        ),
        migrations.RemoveField(
            model_name="contabancaria",
            name="nome_banco",
        ),
        migrations.CreateModel(
            name="ComiteDiario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_negociacao", models.DateField()),
                ("data_vencimento", models.DateField()),
                (
                    "receita_despesa",
                    models.CharField(
                        choices=[("receita", "Receita"), ("despesa", "Despesa")],
                        max_length=20,
                    ),
                ),
                ("historico", models.CharField(max_length=255)),
                ("numero_nota", models.IntegerField()),
                ("valor_liquido", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "tipo_movimento",
                    models.CharField(
                        choices=[("compra", "Compra"), ("financeiro", "Financeiro")],
                        max_length=20,
                    ),
                ),
                (
                    "decisao",
                    models.CharField(
                        choices=[
                            ("pagar", "Pagar"),
                            ("adiar", "Adiar"),
                            ("corrigir", "Corrigir"),
                            ("transferir", "Transferir"),
                            ("conciliar_adiantamento", "Conciliar adiantamento"),
                            ("saldo_em_conta", "Saldo em conta"),
                        ],
                        max_length=40,
                    ),
                ),
                ("data_prorrogada", models.DateField(blank=True, null=True)),
                (
                    "centro_resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comites_diarios",
                        to="app.centroresultado",
                    ),
                ),
                (
                    "de_banco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comites_transferencia_origem",
                        to="app.banco",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comites_diarios",
                        to="app.empresa",
                    ),
                ),
                (
                    "empresa_titular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comites_diarios",
                        to="app.empresatitular",
                    ),
                ),
                (
                    "natureza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comites_diarios",
                        to="app.natureza",
                    ),
                ),
                (
                    "para_banco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comites_transferencia_destino",
                        to="app.banco",
                    ),
                ),
                (
                    "para_empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comites_transferencia_destino",
                        to="app.empresatitular",
                    ),
                ),
                (
                    "parceiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comites_diarios",
                        to="app.parceiro",
                    ),
                ),
            ],
        ),
    ]
