# Generated by Django 6.0.2 on 2026-04-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_banco_comitediario_refactor_contabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancoPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.IntegerField()),
                ('data_lancamento', models.DateField(blank=True, null=True)),
                ('data_balanco_patrimonial', models.DateField()),
                ('empresa_balanco_patrimonial', models.CharField(choices=[('mmtg', '1 - MMTG'), ('safia_distribuidora', '1 - SAFIA DISTRIBUIDORA'), ('ca', '2 - C.A'), ('csm', '3 - CSM')], max_length=32)),
                ('tipo_movimentacao', models.CharField(choices=[('ativo', 'Ativo'), ('passivo', 'Passivo')], max_length=16)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancos_patrimoniais', to='app.empresa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'numero_registro'), name='uq_balanco_patrimonial_empresa_numero_registro')],
            },
        ),
    ]
