# Generated by Django 6.0.2 on 2026-04-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_balancopatrimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancoPatrimonialAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_bp', models.CharField(blank=True, choices=[('mmtg', 'MMTG'), ('safia', 'SAFIA'), ('ca', 'CA'), ('csm', 'CSM')], default='', max_length=16)),
                ('categoria', models.CharField(blank=True, choices=[('veiculos', 'Veiculos'), ('maquinas', 'Maquinas'), ('industria', 'Industria'), ('imovel', 'Imovel'), ('outros', 'Outros')], default='', max_length=32)),
                ('sub_categoria', models.CharField(blank=True, default='', max_length=120)),
                ('secao', models.CharField(blank=True, default='', max_length=120)),
                ('nivel', models.CharField(blank=True, default='', max_length=120)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('patrimonio', models.CharField(blank=True, default='', max_length=255)),
                ('placa', models.CharField(blank=True, default='', max_length=40)),
                ('local', models.CharField(blank=True, default='', max_length=255)),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ano', models.CharField(blank=True, default='', max_length=32)),
                ('valor_bem', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_real_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_venda_forcada', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_declarado_ir', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('quitacao', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('alienacao', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('parcelas', models.IntegerField(blank=True, null=True)),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('passivo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status_financiado', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=120)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancos_patrimoniais_ativos', to='app.empresa')),
            ],
        ),
    ]
