# Generated by Django 6.0.2 on 2026-04-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_balancopatrimonialativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancopatrimonial',
            name='tipo_movimentacao',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('passivo', 'Passivo')], default='', max_length=16),
        ),
    ]
