# Generated by Django 6.0.2 on 2026-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_precificacaocenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precificacaoprodutoacabadodespesa',
            name='log_frete_rota',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
