# Generated by Django 6.0.2 on 2026-04-13 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_precificacaoprodutoacabadodespesa_log_frete_rota'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_baixa', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('nome_fantasia_empresa', models.CharField(blank=True, default='', max_length=220)),
                ('receita_despesa', models.CharField(blank=True, default='', max_length=30)),
                ('parceiro', models.CharField(blank=True, default='', max_length=80)),
                ('nome_parceiro', models.CharField(blank=True, default='', max_length=220)),
                ('numero_nota', models.CharField(blank=True, default='', max_length=50)),
                ('natureza', models.CharField(blank=True, default='', max_length=80)),
                ('descricao_natureza', models.CharField(blank=True, default='', max_length=220)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_a_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('descricao_tipo_operacao', models.CharField(blank=True, default='', max_length=220)),
                ('descricao_centro_resultado', models.CharField(blank=True, default='', max_length=220)),
                ('plano_contas_tipo_movimento', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_dre', models.CharField(blank=True, max_length=120, null=True)),
                ('dfc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dre_registro', to='app.fluxodecaixadfc')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dre_registros', to='app.empresa')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'data_baixa'], name='app_dre_empresa_19110d_idx'), models.Index(fields=['empresa', 'data_vencimento'], name='app_dre_empresa_ba395e_idx')],
            },
        ),
    ]
