# Generated by Django 6.0.2 on 2026-04-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_dre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precificacaoprodutoacabadoprecovenda',
            name='situacao',
            field=models.CharField(choices=[('direcao', 'DIRECAO'), ('gerente_comercial', 'GERENTE CML'), ('supervisor', 'SUPERVISOR'), ('vendedor', 'VENDEDOR')], default='direcao', max_length=24),
        ),
    ]
