# Generated by Django 6.0.2 on 2026-04-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_descricaobp_balanco_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocargosalario',
            name='contato',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
